### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by jeduan** [jeduan/cordova-plugin-facebook4#201]
Hi. I've been overwhelmed with the amount of support requests from the community, and this with the fact that I'm no longer using cordova in the day job has made it very difficult to keep up with this repository.

I'm looking for individual contributors or companies to step up and continue the tasks that are left such as having better docs and better integration with the Facebook parts I didn't use and haven't received much testing.

I'll allocate some hours to onboard anyone interested.

**Comment by Hirbod** [comment]
well I started to merge some stuff and delete invalid tickets. npm-account is needed for publishing

**Comment by jeduan** [comment]
Thanks I'll add you tomorrow. Is the username the same?

**Comment by robertarnesson** [comment]
I'm interested

**Comment by jeduan** [comment]
@robertarnesson how can I help to get you started?

**Comment by robertarnesson** [comment]
@jeduan can you also add me on npm? https://www.npmjs.com/~arnesson

**Comment by jeduan** [comment]
@robertarnesson added

**Comment by jacquesdev** [comment]
Hi @jeduan 

I have been trying to figure out what is going on with https://github.com/Wizcorp/phonegap-facebook-plugin since the issues and PR's are just growing but it seems nothing is happening. Is that project no longer active, and does it mean this project will essentially take the plugin forward?

If yes, I am happy to assist you with this project where I can.
