### ISSUE TITLE
file is universal (4 slices) but does not contain a(n) armv7s slice

### ISSUE THREAD

**Issue by quintonn** [jeduan/cordova-plugin-facebook4#237]
I am writing a mobile app using Visual Studio 2015 with Apache Cordova.
I've added this plugin as well as google amob pro into my application.
I already had to make some weird change to get the code to compile on Android.
Now when i try and run it on an ios device i get the following error:

"file is universal (4 slices) but does not contain a(n) armv7s slice: ../Plugins/cordova-plugin-facebook4/FBSDKShareKit.framework/FBSDKShareKit file '../Plugins/cordova-plugin-facebook4/FBSDKShareKit.framework/FBSDKShareKit' for architecture armv7s"

From what I've found is that the architecture armv7s is not supported by the plugin. I am hoping this is something that can be fixed by simply recompiling the plugin code with support for this architecture, but somehow i feel this might not be the case.
Is this something someone could have a look at?

**Comment by robertarnesson** [comment]
armv7s is not standard anymore as of xcode 6, and the facebook sdk does not come with support for it. I think your only option is to use an older version of the plugin if you need to support old armv7s devices

**Comment by cstinfotech** [comment]
I build an app using cordova , ionic and visual studio 2015, cordova - ios 4.3.1  and plugin cordova-plugin-facebook4@1.7.0. App is successfully build for Android both (Debug and Release ), iPhone ( Debug). But when it is build for IOS release , the following issue is encountered.
file is universal (4 slices) but does not contain a(n) armv7s slice

It is also mentioned in this thread of communication  that this issue is released. Please let me the details where i can get its solutions.
