### ISSUE TITLE
ios9 on native app is still no solution there?!

### ISSUE THREAD

**Issue by hossam9995** [jeduan/cordova-plugin-facebook4#245]
when fire the app login it take you to the safari or web browser not to the native app when use ios9

it there any solution for this problem  or its still no solution ?!

i try to use this solution from this link but its won't  work
https://developers.facebook.com/docs/ios/ios9

if there any solution please tell me about it 

thanks

**Comment by jeduan** [comment]
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by sebrojas14** [comment]
So, are you saying that in iOS 9 is not possible to use app login? only browser?

**Comment by jeduan** [comment]
It's Facebook's recommended approach and the only one this plugin will implement. If it's good enough for Instagram and Lyft, it should be good enough for everyone else.

**Comment by sebrojas14** [comment]
Got it.

**Comment by jeduan** [comment]
@1N50MN14 so write it then! Never said I'd never accept a pull request.

**Comment by 1N50MN14** [comment]
You did say "It's Facebook's recommended approach and the only one this plugin will implement" which sounded pretty determined to me. I was just politely sharing a different point of view, no need to get angry mate.

**Comment by 1N50MN14** [comment]
@jeduan The behaviour is hardcoded in the FB SDK; the only way to fix that is by making some minor alterations to the SDK itself, which I did as you can see here: https://github.com/1N50MN14/facebook-ios-sdk

I'm not sure if this can be accomplished via a hook (or if it makes sense to do so, i.e. alter, compile, embedd); anyway I included the build in my fork here https://github.com/1N50MN14/cordova-plugin-facebook4 and I'm getting the desired behaviour.

Question: Did you use `build_framework.sh` or `build_framework_distribution.sh` for your build? I'm not sure how to submit this as a PR, any advice?

**Comment by jeduan** [comment]
Wow… figured there'd be a way to make `FBSDKLoginBehavior` do what you wanted, but forking the SDK is a bit too much. If forking and recompiling the SDK it's the only way to do it, I'd advise making a blog post explaining the process…

**Comment by 1N50MN14** [comment]
@jeduan The guys over at FB are pretty much hardcoding the thing like so

`BOOL useNativeDialog = [configuration useNativeDialogForDialogName:FBSDKDialogConfigurationNameMessage];`

This *always* returns false, it completely ignores whatever value you pass via the `loginBehavior` property which is supposed to define the login behaviour. 

One thing I thought of is to do this as an optional configuration for the plugin (something like --rebuildnative) which would download, alter and rebuild the SDK on the fly for those who chose to do so and document that in README (instead of a blog). What do you think?

By the way how did you build the SDK if I may ask? did you use `build_framework.sh`or `build_framework_distribution.sh`(both seem to be working equally fine for me)
