### ISSUE TITLE
"publish_actions" permission in read authorization

### ISSUE THREAD

**Issue by daniel7558** [jeduan/cordova-plugin-facebook4#282]
Hi,
It seems to me that sometimes it is not possible to get publish_actions permission. With the following code it worked yesterday perfectly and now I get an error - but nothing was changed in the code from yesterday to today.
Code:

```
facebookConnectPlugin.login(["publish_actions"], function(userData) {
                console.log("UserInfo: ", userData);
                facebookConnectPlugin.getAccessToken(function(token) {
                    console.log("Token: " + token);

                    /* do stuff with token */
                });
            },
            function (error) {
                console.error(error);
            }
        );
```

Error message:
` Cannot pass a publish or manage permission (publish_actions) to a request for read authorization`

I'm running it with Cordova 6.3.0 and Android 6.0.

**Comment by circuitrider** [comment]
Is it possible that during your tests when it was working, you were trying to authenticate with a user who had already granted that permission? And in the time since you revoked the permission from that user's approved app list on facebook.com?

I know I've been caught in a similar moment of confusion when something seemed to be working previously due to something like this.

**Comment by daniel7558** [comment]
Thanks, I checked it and if I first ask for "email" permission and then for "publish_actions" permission it works. But I don't want to let my users accept two seperate requests. 
So when the user has never accepted anything and I ask for "publish_actions" I get this error. Any ideas on how to solve this?

**Comment by circuitrider** [comment]
What you're seeing is normal and expected behavior. The publish_actions claim is always separate in user confirmation from the "readonly" claims like email, etc. Sorry there isn't a workaround, it is enforced by Facebook. It makes sense from their perspective for sure, this way user's are more aware that an app they are registering with will essentially be able to impersonate them on their wall in a way, which definitely is very high criticality and should be called out independent of the readonly claims.

**Comment by daniel7558** [comment]
Ah ok, thanks for your explanation!

**Comment by learningfun1234** [comment]
Daniel, 

How are you calling plublish_actions now? publish_actions request is just not working for me.  How did this work "I checked it and if I first ask for "email" permission and then for "publish_actions" permission it works"?

Thanks!

**Comment by daniel7558** [comment]
I'm using it like:

    facebookConnectPlugin.login(["email"], function(userData) {
                console.log("UserInfo: ", userData);

                getAccessToken(function(token) {
                    facebookConnectPlugin.login(["publish_actions"], function(userData) {
                            console.log("UserInfo: ", userData);
                            facebookConnectPlugin.getAccessToken(function(token) {
                                console.log("Token: " + token);

                                successfn();
                            });
                        },
                        function (error) {
                            console.error(error);
                            errorfn();
                        }
                    );
                });
            },
            function (error) {
                console.error(error);
                errorfn();
            }
        );

    },

**Comment by learningfun1234** [comment]
Thanks a lot :+1:
