### ISSUE TITLE
Can't access $scope vars inside the callback success/error functions

### ISSUE THREAD

**Issue by DanieleRatti** [jeduan/cordova-plugin-facebook4#300]
Using cordova-plugin-facebook4 on ionic and running on iOS, the $scope variables seems to be untouchable:

```
$scope.token = "no token";
$scope.fbconnected = false;

$scope.gotToken = function(token) {
	alert("got token: "+token); //runned
	$scope.token = token; //seems to be untouched!!!
}
	
facebookConnectPlugin.login(["public_profile", "email", "user_friends"],
	function (userData) {
		alert("fb success"); //runned
		$scope.fbconnected = true; //seems to be untouched!!!
		
		facebookConnectPlugin.getAccessToken(function(token) {
			$scope.gotToken(token);
		});
	},
	function (error) {
		alert("I do not enter here");
	}
);
```

The alerts are called correctly while the $scope.variables don't change their value.

The strange thing is that the $scope.gotToken function is called so the $scope is accessible inside the callback function but the variables inside it not!

**Comment by fredgalvao** [comment]
Can you replace 
```js
$scope.fbconnected = true;
```

with
```js
console.log('$scope', Object.prototype.toString.apply($scope));
console.log('$scope.fbconnected', Object.prototype.toString.apply($scope.fbconnected));
$scope.fbconnected = true;
```
and see the output of those 2 logs?

**Comment by DanieleRatti** [comment]
I get the correct values:

```
$scope [object Object]
$scope.fbconnected false
```

And I discovered that actually the $scope vars are modified and the issue is a fault in the view update.

In fact when a given $scope variable is updated from the facebook callbacks this is NOT reflected on the view and I fixed by calling a the `$scope.$apply();` method before close each callback.

**Comment by fredgalvao** [comment]
Yeah, that's angularJs knowledge[1]. Good to know it's not some ghost in the facebook plugin :wink:,

From angular 1.x docs([source](https://docs.angularjs.org/api/ng/type/$rootScope.Scope)):
> ## $apply([exp]); ##
**$apply() is used to execute an expression in angular from outside of the angular framework. (For example from browser DOM events, setTimeout, XHR or third party libraries).** Because we are calling into the angular framework we need to perform proper scope life cycle of exception handling, executing watches.
