### ISSUE TITLE
Logout doesn't deauthorize user

### ISSUE THREAD

**Issue by kinoli** [jeduan/cordova-plugin-facebook4#328]
When you logout it does not deauthorize the user, so when you go to login again, it says the person has already authorized and they don't have to enter their login credentials again. This is bad. A logout should force a person to login again. How would you login with another fb account?

Is there any work around for this?

**Comment by Hirbod** [comment]
Deauthorizing would mean reverting the facebook-access. We can't do that. In order to use another FB-Account, you will have to logout from FB-Safari and re-login. This is the only way, and all other big players on the market doing the same within there app. Session Sharing with the new SFWebViewController behave like that.
