### ISSUE TITLE
minSdkVersion is conflicting with crosswalk

### ISSUE THREAD

**Issue by v3ss0n** [jeduan/cordova-plugin-facebook4#351]
when latest crosswalk version is used , it requires minSdkVersion='16' and it conflicts with minSdkVersion='15' of this plugin and causing build errors.

**Comment by pke** [comment]
Same here. Why is this even in the plugin config?

**Comment by pke** [comment]
I wonder why cordova does not have a proper special handling of this property in place. It seems to just dump all properties in the final manifest. It should take special care for this property to write only the highest version to the final manifest.

Anyway, we can take this strange cordova behaviour to our advantage and just include the CrossWalk plugin **after** the facebook plugin in the `config.xml`.
Then remove the platform and re-add the platform will make this work, because first the facebook plugin writes its minSDK of 15 to the Android manifest and then the CrossWalk plugin overrides this value with its minSDK of 16.

**Comment by v3ss0n** [comment]
some install crosswalk first : ember-cordova and ionic .

**Comment by pke** [comment]
@v3ss0n It doesn't matter. Important is the order of the plugins in the `config.xml` file. Put crosswalk after this plugin.

**Comment by pke** [comment]
@fredgalvao so you mean we can specify the minimumSDK preference in `config.xml`?

**Comment by fredgalvao** [comment]
@pke Oh yeah. [All of them](https://cordova.apache.org/docs/en/latest/config_ref/index.html#preference).

These are all valid `<preference>`s
- `android-maxSdkVersion(integer)`
- `android-minSdkVersion(integer)`
- `android-targetSdkVersion(integer)`


I use this on my own `root/config.xml`:
```xml
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-targetSdkVersion" value="23" />
```

And I use crosswalk+push+facebook. My own settings always wins.

**Comment by v3ss0n** [comment]
Thanks a lot!!
