### ISSUE TITLE
not working when app not installed and facebook open in browser

### ISSUE THREAD

**Issue by isunnynegi** [jeduan/cordova-plugin-facebook4#380]
dear,
this plugin is not working when, their is no Fb app on device, then its open in browser, it always return error

**Comment by VinceOPS** [comment]
Hi, same issue here.
I did the proper configuration locally (platform `browser` installed, plugin installed, everything related to Facebook whitelisted) and remotely (added my URL as a "Valid OAuth redirect URI"), but I keep seeing this error in the console output:

> Refused to display 'https://m.facebook.com/login.php?skip_api_login=1&api_key=62foobarfoobar3&s…lay=touch&locale=en_US&logger_id=b4d312d2-252d-4da7-921d-foobarfoobar17&_rdr' in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by Neo1975** [comment]
Hi,
I have same problem, but I don't have  cordova-plugin-inappbrowser installed.
I'm using ionic 2 with a very simple login without Facebook App, a window appears after confirm to add application i stay in a white page until press "Done" cancelling request.

Any suggestion?

**Comment by razvantomegea** [comment]
+1

**Comment by hugobessa** [comment]
Having the same issue in android. The error message is the same one that appears when the facebook app is in development mode: "app not setup this app is still in development mode and you don't have access to it".

**Comment by veronicabend** [comment]
Neo1975 did you find a way to solve this? I have the same problem. Goes to facebook page to authorize app, after authorizing it stays at a white facebook page but doesn't go back to the app.

**Comment by Charlywhat** [comment]
I was facing the same problem. No Facebook app and no inappbrowser plugin installed. When trying to login from plugin, facebook login popup was shown, after logging in, popup never hid, but the "Loading" message remained. On Android Studio logcat I could see the Refused to display <the_url> in a frame because it set 'X-Frame-Options' to 'DENY'.
What I did was add the inappbrowser plugin and then removed it, made a new build and the problem was gone (I could log in and out many times without problems). This is weird, but it definetely has to do something with the inappbrowser plugin.

**Comment by DanielRiera** [comment]
The problem is that the Facebook SDK uses window.open, inAppBrowser replaces window.open variables, but this happens in the deviceReady event.

This problem can be solved as well.

Before the deviceReady event you have to create a global variable.

`var browserDefault = window.open;`

Now window.open is safe.

After the deviceReady event the following.

```
delete window.open;
window.open = browserDefault;
myBrowserExtra = cordova.InAppBrowser;
```

Now we can call to open with cordova-plugin-inappbrowser as well

`myBrowserExtra.open (....);`

And cordova-plugin-facebook4 will continue to function normally since we have eliminated overwriting

**Comment by OsiBE** [comment]
Can't get it to work. How/where to implement that in an Ionic2-App?

**Comment by mukulsoftwap** [comment]
I have same issue in ionic 2, some time its work fine but most of cases its not working please have a look into this bug.

**Comment by ocsi94** [comment]
The problem is based on InAppBrowser plugin.
Fix:

go to plugins/cordova-plugin-inappbrowser/plugin.xml
find and under this remove this line :
remove browser platform and add it again
Reason :
The inappbrowser plugin overwrite the native window.open.
You still can use the plugin with cordova.InAppBrowser.open as you can see at the clobbers
I also checked the source of ionic implementation its try to use first cordova.InAppBrowser.open if avaliable.

Handicap :
-Its do not overwrite window.open anymore, only in browser platform, usualy its not a problem.
-Becouse i dont want to commit the plugins folder into version control is created a script where i replace it.

**Comment by claudiulazar** [comment]
@ocsi94 I for example do not have the cordova-plugin-inappbrowser plugin added to my project. I have just the cordova-plugin-facebook4 plugin added.

**Comment by claudiulazar** [comment]
So it seems that if you are not logged into facebook in the browser it will show the browser facebook page which will ask you "**How do you want to log in?**" **and offer you sign in via native facebook app or sign in with phone number/email.** And from there you can choose the facebook app and open in and get the access token you desired.... fucking hell
