### ISSUE TITLE
What ever happened to old fashioned promises?

### ISSUE THREAD

**Issue by jspenc72** [jeduan/cordova-plugin-facebook4#41]
Anyone interested in promisifying this plugin with bluebird?

**Comment by jeduan** [comment]
The success/error callbacks are not great but it's the standard Cordova interface for plugins.

That being said, as much as I love Bluebird for getting me into promises, it's a massive dependency, so I wouldn't be in favor of adding it to this project. A promisifying solution based on native promises such as [this](https://github.com/jeduan/cordova-plugin-crop/blob/master/www/crop.js#L8-L12) would be preferred

**Comment by fredgalvao** [comment]
That requires a Promise polyfill to work multiplatform, and there's a few lengthy discussions at the cordova mailing list over whether that's an interesting thing and how far deep should the polyfill go.
As far as I remember, they decided to let it be a shallow plugin that other plugins could depend on, instead of having plugins with huge and significant dependencies like Bluebird (awesome project btw). However, I'm still to see said plugin alive.

## Possible workaround ##
That said, you might wanna look at the [ng-cordova](http://ngcordova.com/docs/plugins/facebook/) project, if you're working with angular.

**Comment by jeduan** [comment]
Yeah, what @fredgalvao just said. Just a quick note that Promises are now native to iOS >= 8.0 and Android if targeting >= KitKat either natively or using crosswalk (which you should honestly), so no need to polyfill IMHO.
