### ISSUE TITLE
Login doesn't work on IOS and Android only in Browser 

### ISSUE THREAD

**Issue by LukasBlu1** [jeduan/cordova-plugin-facebook4#421]
When I log in via ios or android the login dialog appears but after login no success function is fired. In Browser all works fine.

**Comment by firoze** [comment]
having the same issue here as well

**Comment by LukasBlu1** [comment]
Do you have a soloution?

**Comment by stefanuswendy** [comment]
i have same issue, still no solution found. please help

**Comment by firoze** [comment]
the problem seems to be that the callbacks (success or error) from `facebookConnectPlugin.login` never fire. therefore, as a (temporary, sometimes finicky) workaround, I set a flag in `localStorage`, and wait for the `'resume'` event to fire with `$ionicPlatform.on('resume', checkFbStuff);`

the `'resume'` event fires more consistently than the callbacks from the plugin. once that event is fired, I did `facebookConnectPlugin.getLoginStatus` and depending on whether the login process was successful or not, you will get the same response (data or error) with `getLoginStatus` as with `login`

this didn't work for me the first few times, so I ended up wrapping the `getLoginStatus` check inside a 350ms timeout, and I've had better luck since then

**Comment by stefanuswendy** [comment]
recently i got fixed this somehow. did you guys add the facebookConnectPlugin to the window ?
`window.facebookConnectPlugin = facebookConnectPlugin;`
i tried remove the code and directly using the facebookConnectPlugin object then BOOM. callback run back to normal.

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
