### ISSUE TITLE
Open in native Facebook app?

### ISSUE THREAD

**Issue by sean-hill** [jeduan/cordova-plugin-facebook4#46]
Hey I just replaced the Wizcorp facebook plugin with this one. I was hoping that it'd open in the native Facebook app. Does this plugin not do this in iOS 9? Thanks.

I also followed all the Facebook steps found [here](https://developers.facebook.com/docs/ios/ios9).

![img_1482](https://cloud.githubusercontent.com/assets/1205866/9948664/ff52f402-5d59-11e5-995c-18fd6075696c.jpg)

**Comment by jeduan** [comment]
Facebook just changed that in their SDK.

As mentioned in #18 iOS 9 changed the way external apps are opened, so opening the Facebook App needs to accept a dialog twice (once to go app -> Facebook and then to go back Facebook -> app) so that's the likely reason they decided to use what looks like SFWebkitView.

There's a bit more info at their FAQ in https://developers.facebook.com/docs/ios/ios9

**Comment by uofmmike** [comment]
I'm struggling on this one, Is there a way to get this to open in the native app?

**Comment by sean-hill** [comment]
Hey @uofmmike,

The new Facebook SDK is stupid and opens the auth in SFSafariView instead of the native app. There has been a conversation [here](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1116#issuecomment-141945103). The solution was to use the older `v3` version of the Facebook SDK and add in the relevant code in your `.plist` file. Take a look at that thread.

**Comment by daniel-costa** [comment]
Using Parse to register my device, I can't downgrade to a lower SDK. Otherwise, it will simply not compile my Xcode project (conflict between frameworks in the Facebook SDK and Parse SDK).

Am I missing something here?

**Comment by Savankumar-vaishnav** [comment]
Hey This is very bad. I have find out so many solution. Nothing work proper.

**Comment by jeduan** [comment]
As [you already know](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1116#issuecomment-151870143) this is the way the Facebook SDK works now.

**Comment by kaansoral** [comment]
I experience this too, with both the telerik version and this plugin

I have an old wizcorp version in production, luckily that one functions as expected (haven't tried the wizcorp version again yet)
(so it's not an iOS 9 issue, the production one just asks whether the "Facebook" app should be opened, then opens it, and succeeds with the auth)

For me it's not just a browser, but it falls back to web auth, so the user has to manually re-enter their fb password, which beats the purpose

Any ideas?

**Comment by jeduan** [comment]
@kaansoral This has been talked so many times in the issues of this repo. Here's one experiment: [Download the Facebook SDK](https://developers.facebook.com/docs/ios) and run the examples to see if they have _the bug_ too.

**Comment by kaansoral** [comment]
@jeduan yes I see the reports, yet I don't see anything definitive

- Are you saying that this is not a bug and this is how things work now? (high friction)
- Are you saying that this is a bug that will be solved when Facebook updates the SDK?
- Are you saying that there is something wrong with the way I'm doing things and ideally the auth should be native?

I just see closed issues and no information, it would be great if this issue was mentioned in the Readme so others would know what to expect

**Comment by jeduan** [comment]
Again, did you download the SDK and run the examples?

This is the way the SDK works on Version >= 4.5 and it's the solution Facebook's engineers chose because Safari can now share cookies between the FB App and Safari (or SFSafariView in this case).

The reason you're getting the old method with Wizcorp's is because phonegap-facebook-plugin is still on a very old version of the SDK, which, as you noted depends on the user tapping *twice* on a dialog asking to open an external app. If the user doesn't tap "Open" on that dialog, then they're stranded and need to go to Settings before they can do anything. Guessing that's friction on FB's engineer's book.

Anyways, using the latest SDK from Facebook ensures that your app always uses the best method for the phone's version.

**Comment by kaansoral** [comment]
![img_1308](https://cloud.githubusercontent.com/assets/170243/11917331/93bdd602-a70b-11e5-88ba-5d121429b659.jpg)

This is how it appears for me by the way, tested the "Share It!" example app, like you suggested, it seems that one experiences the same issue too, a better auth UI shows up (with the app logo), but again a web one without the auth that exists on the fb app itself (same situation on an iPad too)

At this point I will probably dig up an earlier version of one of the plugins that will let me publish an app update, I will check this plugin and try using earlier version of the SDK as the app invites feature is pretty useful

**Comment by kaansoral** [comment]
As an update, this is the solution: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1206

**Comment by Hirbod** [comment]
Even when there is an option to force the fast app switching flow, once the user decide to click no (in Facebook or inside your app), the dialog won't appear anymore and they will stuck inside the app until they go inside of the settings and toggle the switch. You guys need to accept the new flow. Once this has been normalized, it will be the new standard. Facebook login token will stay there forever as long as they don't remove cookies and local data

**Comment by adyz** [comment]
@Hirbod  -- Where can we "toggle the switch"?

**Comment by Juelcf** [comment]
Hi,

I tried everthing and the facebook login fallbacks always to the Web Dialog

Im using the latest FacebookSDK
also updated the plist LSAApplicationQueriesSchemes

<string>fbapi</string>
        <string>fbapi20130214</string>
        <string>fbapi20130410</string>
        <string>fbapi20130702</string>
        <string>fbapi20131010</string>
        <string>fbapi20131219</string>
        <string>fbapi20140410</string>
        <string>fbapi20140116</string>
        <string>fbapi20150313</string>
        <string>fbapi20150629</string>
        <string>fbauth</string>
        <string>fbauth2</string>
        <string>fb-messenger-api20140430</string>

FacebookConnectPlugin.m in Compiles Sources Ok

WhteListed fb:

Any advice? Im going nuts here
