### ISSUE TITLE
It always opens browser with Facebook page instead of native app

### ISSUE THREAD

**Issue by antonpash** [jeduan/cordova-plugin-facebook4#461]
It always opens browser with Facebook page.
What can i do to make it open native Facebook app?

**Comment by andrewoodleyjr** [comment]
+1

**Comment by antonpash** [comment]
It seems like this behavior is correct...In iOS it opens webpage and if the native Facebook app is installed will be shown appropriate button like "Login with app"
In Android it works with native Facebook app if that is installed

I have another problem...on my iOS device it works like it have to, but on iOS simulator i have this error "There was a problem logging you in.". Any assumptions what it might be?

**Comment by JohnScottMcNerney** [comment]
+1 Facebook APP is fully installed on the iOS device, and logged into.

@antonpash In my experience, simulators will seldom work with anything that is outside the APP you are testing. Anything that requires accessing the APP Store (in-app-purchases), or other APPS (facebook login), I have not had any luck with in the simulator. I end up using Xcode with a real device.

**Comment by JohnScottMcNerney** [comment]
Still an issue, but not a "bug". 

Originally, I thought that the browser being opened was my problem since it opened with an error. Once I correctly added iOS to my developers.facebook.com APP Settings Platforms (even without any Store ID information), the error stopped and the user was able to log in. It's not a pretty log in, since it takes several clicks, but it did work for me.

**Comment by Slavezax** [comment]
In newer SDKs, sadly, you can't choose target platform; web or app. It chooses the best way even though it doesn't seem the best way.

**Comment by antonpash** [comment]
Still have this error "There was a problem logging you in." in iOS >= 9 on the simulator, but there are no any problem on iOS < 9 simulator and on my real device with iOS >= 9...

**Comment by jaybeecave** [comment]
@JohnScottMcNerney did you have any luck once you got everything released.. Its such a bad user experience...

**Comment by JohnScottMcNerney** [comment]
On my released APP it works fine.

I just uninstalled and re-tried. Since I already gave facebook permission for this APP, it didn't even pull up any prompt at all. It just re-confirmed the login and my APP was configured with my facebook account login.

I then removed the permission I gave on Facebook previously, and tried again. It pulled up a nice "continue as John" prompt, clicked yes, APP account was installed perfectly.

Nice user experience.

Tested only on an Android Galaxy S7, my personal phone.

Remember, don't use a simulator for any of this testing. You can get a used wifi-only device online pretty cheap, for a dedicated test device.

**Comment by kurtiev** [comment]
Hi there!
Have the same trouble with iOS only, Android is OK, tested on real devices, both platforms.
Any news with it?

**Comment by kurtiev** [comment]
Seems like it was deprecated in Facebook SDK.
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Facebook moved away from opening the native app for login in its SDK several years ago.
