### ISSUE TITLE
facebookConnectPlugin showDialog on success returns nothing

### ISSUE THREAD

**Issue by siddhant-sankhe** [jeduan/cordova-plugin-facebook4#495]
`facebookConnectPlugin.showDialog({
    method: "share",
    picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
    name:'Test Post',
    message:'First photo post',
    caption: 'Testing using phonegap plugin',
    description: 'Posting photo using phonegap facebook plugin'
  }, function (response) {
    console.log(response)
  }, function (response) {
    console.log(response)
  }
);`

i m using the exact same snippet , but from few days it returns nothing on success response , i haven't touched the plugin code  , can someone help please

**Comment by codecrab-studios** [comment]
I am facing the same issue too.

**Comment by peterpeterparker** [comment]
Not sure, but I googled a bit the subject today, because I'm facing the same error, and I kind of have to feeling that doesn't work anymore, because now, like for "sharing", the "feed" action also need the "publish_actions" permission to be granted to return a value after the action is executed.

See "post_id" in response in following documentation https://developers.facebook.com/docs/sharing/reference/feed-dialog

"post_id" was deprecated for 6 months after 12th October 2016 => till 12th May 2017

**Comment by whiterook6** [comment]
how does one request the publish_actions permission?

**Comment by peterpeterparker** [comment]
Close, inactivity
