### ISSUE TITLE
Can't get the latest using the the directly from git plugin add way on android

### ISSUE THREAD

**Issue by snakeman21** [jeduan/cordova-plugin-facebook4#497]
I'd like to be able to use the latest directly from git since it has the iOS checking for permissions method. This works fine on iOS, but throws this error on Android 7.0

```
Error: /Users/jonl/sites/spacecraft/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/jonl/Sites/spacecraft/platforms/android/AndroidManifest.xml:37:9-186 Error:
	Element activity#com.facebook.FacebookActivity at AndroidManifest.xml:37:9-186 duplicated with element declared at AndroidManifest.xml:17:9-246
/Users/jonl/Sites/spacecraft/platforms/android/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

```

**Comment by viking2917** [comment]
Same for me...

**Comment by jacquesdev** [comment]
Hi there - so just a note it seems that this is being caused by the wrong version in plugin.xml. I have created a PR which should fix this issue #509.

In the meantime, here is an alternative/temporary solution to fixing it, https://stackoverflow.com/a/44311407/1280740, if you need to use the latest version 1.9.0, as opposed to version 1.7.4.

**Comment by jacquesdev** [comment]
@jeduan - unfortunately that did not fix the issue. I am still getting

`* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.`

Perhaps this should be re-opened, because everyone is switching back to 1.7.4, which seems to be the last npm version that worked.

**Comment by fredgalvao** [comment]
@jacquesdev This is most surelly not related to the alpha1 version issue, so I'll reopen this.

@snakeman21 it seems like the output of your build log is incomplete. Would you mind providing the following info:
- exact plugin version installed
- cordova version
- platforms versions
- installed plugins
- full build output

**Comment by peterpeterparker** [comment]
Same same I close it for inactivity reason
