### ISSUE TITLE
Publish Permissions issue

### ISSUE THREAD

**Issue by siddhant-sankhe** [jeduan/cordova-plugin-facebook4#544]
I need to pass publish_actions permission , but plugin wont allow the publish_actions and other read permissions and i cannot pass permission in graph api call i.e. " facebookConnectPlugin.api " method call because the post data is not getting read in this method.

please help :(

**Comment by whiterook6** [comment]
We have the same problem. Without `publish_actions` we cannot get the post_id for whenever we publish:

```
facebookConnectPlugin.showDialog({
	method: 'share',
	href: 'http://google.com',
	caption: 'test post please ignore',
	description: 'test description please ignore',
}, (response) => {
	debugger;
	console.log('success:');
	console.log(response); // always an empty object
}, (error) => {});
```

But you cannot pass `publish_actions` in the login request:

```
facebookConnectPlugin.login([
	'public_profile', 'email','publish_actions'
], (response) => {
	console.log('success logging in!');
}, (error) => {
	console.log('error logging in:');
	console.log(error);
});
```

It does work if you call it a second time to grant that permission. We have this workflow:
1. Login like normal, with only public_profile and email for permissions.
2. Click a button to share to wall
3. Check permissions of logged in user
3.1. If user has 'publish_actions', go ahead
3.2. Otherwise, login again with `publish_actions` as the permission. It shows a dialog asking to give the app permission to post to your wall.

**Comment by siddhant-sankhe** [comment]
Thank you for the info bro.

**Comment by peterpeterparker** [comment]
post_id is decrepated by Facebook
