### ISSUE TITLE
Login (Especially "facebookConnectPlugin.api") Doesn't Work

### ISSUE THREAD

**Issue by Andalusio** [jeduan/cordova-plugin-facebook4#608]
##Revisiting this plugin and noticed that the codes fall apart after signing in, then reaching the "facebookConnectPlugin.api". My app obviously couldn't fetch any data, and didn't execute the codes that follow the Facebook codes.

Example:
 
function fbLogin()
{
	var fbLoginSuccess = function (response) {
		//console.log("UserInfo: ", userData);
		miniMe = response.authResponse.userID;
		if (response.status == "connected")
		{
			facebookConnectPlugin.getAccessToken(function(token) {
				//console.log("Token: " + token);
				facebookConnectPlugin.api("/"  + miniMe, ["public_profile", "email"],
					function onSuccess (result) {
						gamerID = result.id;
						gamerName = result.first_name;
						gamerSurname = result.last_name;
						gamerEmail = result.email;

						//Other codes here.

					}, function onError (error) {
						//console.error("Failed: ", error);
						errorMessage();
					}
				);
			});
		}
		else
		{
			errorMessage();
		}
	}
	//
	facebookConnectPlugin.login(["public_profile", "email"], fbLoginSuccess,
	function (error) {
		//console.error(error)
		errorMessage();
 	});
}

**Comment by kronicali** [comment]
Did you solve this issue or found a work around? Having a similar issue.

**Comment by Andalusio** [comment]
Apparently, the tutorial left out one thing: you MUST type in the accesstoken. For example:
 
 fbLoginSuccess = function(userData){
     facebookConnectPlugin.getAccessToken(function(token){
      facebookConnectPlugin.api("me/?fields=first_name,last_name,id&access_token="+token+"", ["public_profile"],
      ......

Note the '&access_token="+token+"",' part. 
 
Wish you the best!

**Comment by peterpeterparker** [comment]
@Andalusio could you submit a PR to improve the `README` about this?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I've updated the README there to make it clear that developers must include an access token.

**Comment by federrico7** [comment]
> This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I've updated the README there to make it clear that developers must include an access token.

Hi, friend.
I use cordova-plugin-facebook4, because we have cordova 8 and we cannot update it because our core is old, node js and angularjs.
My question is whether the changes Facebook is going to make now can impact my project. Could you help me with that please?



 
   
 Facebook Notice
 
Follow these steps to prevent a disrupted user experience
 
 
We’ve been monitoring an increase in phishing attempts on Android embedded browsers, also known as WebViews. Because of this, we will no longer support this method of Facebook Login and your users will not be able to log in using Android embedded browsers beginning October 5, 2021. Until then, we will continue to prevent access to Facebook Login on embedded browsers for certain users we deem high-risk in an effort to prevent malicious activity.
To avoid a disrupted user experience, please use the following checklist:
Ensure that you have upgraded to version 8.2.0 (or later) of the Facebook SDK for Android. If your app is built to target Android 11 (API level 30) and your users are on Android 11, alternative non-webview login mechanisms provided by the SDK will not work unless you upgrade to or past 8.2.0.
Ensure that you are NOT setting LoginBehavior = WEB_VIEW_ONLY.
Ensure that your app has configured support for Custom Tabs properly. (Not sure what Custom Tabs are? Check here.) To test this, ensure that you have a browser compatible with Custom Tabs (example browsers that support Custom Tabs include Chrome, Samsung Browser, etc). Next, delete the Facebook app from your device if you have it installed. Finally, login from your app. You should see a window open in the external browser rather than in a native WebDialog.
If you do not see an external browser launch, follow these instructions:
Option 1:
Ensure your app is using version 8.2.0 or later of the Facebook SDK for Android. If so, you should not need to make any modifications to your Android manifest. If you have any items referencing “CustomTabMainActivity” or “CustomTabActivity”, remove them.
Option 2:
Configure your Custom Tabs intent filter exactly following the instructions here.
Try Option 1 first and then use Option 2 if Option 1 does not work after testing. There may be cases where we cannot automatically configure your intent filter because of mismatches between the defined $ {applicationId} constant and your package name.
If you have already completed steps 1-3 and have released your app to users, users who are on older versions of your application will see an error message when they attempt to login from a webview, prompting them to upgrade to the newest version of your application. If you have mechanisms to force auto-upgrades for existing installations of your application or to prompt your users to upgrade, we encourage you to use them to limit affected users.
If your app is used primarily on devices which are unable to host the login experience in an external browser, we encourage you to integrate Device Login as an alternative login mechanism.

**Comment by noahcooper** [comment]
@federrico7 I'd strongly recommend moving to `cordova-plugin-facebook-connect`. The fact that you're using AngularJS shouldn't matter.

This plugin uses version 5 of the Facebook SDK, so by default, on October 5, logging in on Android will stop working when Facebook deprecates logging in using webview. You _could_ try using the `FACEBOOK_ANDROID_SDK_VERSION` preference to use at least v8.2.0 of the SDK, but you are likely to run into other problems if you do so.

**Comment by federrico7** [comment]
> @federrico7 I'd strongly recommend moving to `cordova-plugin-facebook-connect`. The fact that you're using AngularJS shouldn't matter.
> 
> This plugin uses version 5 of the Facebook SDK, so by default, on October 5, logging in on Android will stop working when Facebook deprecates logging in using webview. You _could_ try using the `FACEBOOK_ANDROID_SDK_VERSION` preference to use at least v8.2.0 of the SDK, but you are likely to run into other problems if you do so.

@noahcooper  Thank you very much for answering!
I've been researching, updating cordova 8 to newer versions (to be able to use cordova-plugin-facebook-connect) is practically doing the app again. The app is made with nodejs 8, ionic 3 and angular js, everywhere it appears that it is almost impossible to update it since it requires doing the whole app again.
You decide that you can put only the cordova-plugin-facebook-connect plugin without problems?
Thank you.
