### ISSUE TITLE
I'm so happy that this plugin is now ALIVE

### ISSUE THREAD

**Issue by Slavezax** [jeduan/cordova-plugin-facebook4#647]
Thanks to jeduan for creating an amazing plugin helping to thousands of people. However we need to accept the fact that he does not maintain it anymore. It seems @peterpeterparker just took the control of plugin and keeping it up-to-date.

I couldn't be happier.

Well done and keep up the good work.

**Comment by peterpeterparker** [comment]
I'm joining you to praise the work of @jeduan in order to create, develop and support this plugin, such an awesome contribution and job!

I didn't took over the "control" at all, but like I said in #629, this plugin is a major piece of my app and therefore, as long as I use it, don't run out of money/business, will try to be around when breaking changes will be needed (like it was the case recently with the new Facebook iOS SDK)

But don't except from me to answer every questions and develop new features, I'll just not have the time you know

And from a more personal point of view, thx for your msg, it really made my day 😁

P.S.: I close this issue, if you are interested by the subject or to be a maintainer, follow #629
