### ISSUE TITLE
Facebook SDK missing after installing this plugin

### ISSUE THREAD

**Issue by JeremyColton** [jeduan/cordova-plugin-facebook4#699]
Using Android 8 (API 26).
Cordova Cli 6. 5.0
Android Cordova 6.5.0

I installed the plugin via:

>cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="XXXXX" --variable APP_NAME="YYYYY"
Fetching plugin "cordova-plugin-facebook4@~2.3.0" via npm
Installing "cordova-plugin-facebook4" for android
Subproject Path: CordovaLib
Subproject Path: FacebookLib
Saved plugin info for "cordova-plugin-facebook4" to config.xml

'cordova plugins ls' shows the plugin is installed:
cordova-plugin-facebook4 2.3.0 "Facebook Connect"

The newly created \platforms\android\FacebookLib folder does not have a src folder.

But now my Eclipse Android project won't compile since the plugin's ConnectPlugin.java file requires facebook SDK to be on the classpath since it can't find fb packages, eg:
com.facebook.AccessToken
com.facebook.CallbackManager
etc.

The npm page for this plugin says:
"This is a fork of the official plugin for Facebook in Apache Cordova that implements the latest Facebook SDK".

Where is the related Facebook SDK installed to?
How do I link it to my project?

Thanks.
J

**Comment by fredgalvao** [comment]
That's an issue with Eclipse Android, as this plugin doesn't ship the Facebook SDK itself, but rather [links to it using a `framework` cordova tag](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/plugin.xml#L64) (which translates to a gradle dependency).
Your options are:
- try Android Studio (it most certainly has better seamless support for an android project structure than Eclipse Android)
- search online on how to make Eclipse Android understand your gradle dependencies

If you can reproduce the issue showing that another gradle dependency is resolved while facebook's one isn't, then we can start looking for a bug or missing feature.

**Comment by fredgalvao** [comment]
You can always manually download the Facebook SDK and add it to your classpath on Eclipse, but I'd strongly suggest against it.

If you do the whole process of:
- installing the plugin
- running `cordova clean android && cordova build android`

you'll see that it builds successfully (it *needs to*, otherwise we have a huge issue with the plugin). which shows that facebook.plugin->cordova->android.sdk->gradle are doing their job properly.

The things is, cordova was not meant to be used on a native IDE, as the native shell is generated (thus considered an artifact/output). You can mess around and change stuff within that generated shell, but as soon as you need to do anything on the outside (cordova level), you'll most certainly lose/compromise whatever changes you made inside that shell. To sum it up: *you shouldn't need to change/open the native shell itself, and it's actually advised against*.

**Comment by JeremyColton** [comment]
So the `cordova build android` fetches the SDK! That's the missing piece in the puzzle! Thanks.

`cordova clean android` worked.
`cordova build android` broke! It's missing one of my plugins and won't compile!

It's a huge headache upgrading versions of cordova android! I am trying to upgrade from android cordova 5.0.0 to 6.5.0. What's your experience with upgrading?

**Comment by fredgalvao** [comment]
The same as yours, :smile: .
The thing is, it gets easier with time because you get used to the things that usually change, and to the things that can break, so you know where to keep an eye.

I'm hoping you're at least doing `cordova platform rm android && cordova platform add android@latest` instead of `cordova platform update` (the `update` command was never reliable, and it's not even recommended: see this for example https://cordova.apache.org/announcements/2018/02/26/cordova-android-7.1.0.html).

**Comment by JeremyColton** [comment]
Haha, semi-reassuring that the experts also suffer from upgrades!

I am removing and adding the cordova platform as you recommended. But I am not upgrading to the latest (Android Cordova 7.1) since the link you referenced (I already read it a few days ago) says most plugins aren't compatible with it!

It made me decide to only upgrade to Android Cordova 6.4.0 (supports Android 8, API 26 since Google now require this API to be targeted by new apps).

I noticed that Android Cordova 6.4.0 doesn't have a package.json in the app's root. Does this mean your facebook plugin won't install?

**Comment by fredgalvao** [comment]
Cordova has been slowly migrating towards full npm, but it's still not 100% and it has been mostly `config.xml` since forever, so it's expected to not see `package.json` in your app's root. That only means cordova will be working mostly through `config.xml` and through the `plugins` folder, which is fine.

**Comment by JeremyColton** [comment]
No the build failed, it couldn't merge Dex files.
But even if the build passed, within Eclipse, the ConnectPlugin.java would not compile without having the FB SDK on the classpath. I looked at converting the latest SDK from .aar format into an Android project that I can add to Eclipse but it's too error prone. 

I've spent 3 days on this and decided to move to Android Studio to prevent wasting even more time.

Integrating my Eclipse to Android Studio also isn't simple even with the built-in import-from-Eclipse ADT! I decided to create a new Cordova project and slowly migrate my code across! This way I can fix bugs simply as they happen.

Upgrading Cordova sucks and rarely works!

Thanks for all your help.

**Comment by fredgalvao** [comment]
I don't think I can help you anymore on that Eclipse journey, it's way out of the usual cordova development environment imo.

Why are you looking for FB SDK 3.+? This plugin uses FB SDK 4.+, which is not outdated at all.

The way you build your project on Android Studio (or any other JetBrains IDE) will impact how you view the folders in it. I have not used Android Studio to develop a cordova application, so I can't really help you there.

If your application could not build properly through the command line directly with cordova, you should create a new issue with that and make a full detailed reproduction scenario.

But again, my opinion is that you're going the opposite direction by trying to open the native shell of a cordova application on an IDE to change anything. **That's not how cordova apps are meant to be used**.

**Comment by JeremyColton** [comment]
If not Android Studio, which IDE do you use to build cordova apps that run Android?

FB SDK 3.+ because it can compile inside Eclipse (with ADT) since it's a simple android app that I add as a dependency.

I'm building my app from new with Android Cordova 6.4 (since plugins are compatible with it and Android Cordova 7 has many issues according to your last reference). I'll move my plugins one by one into my new app so I can see what breaks and fix it.

**Comment by fredgalvao** [comment]
You're supposed to trust the command line for the main development cycle, so `cordova build android` should do the work 100% of the time (any exception is worth investigating).

The docs do support the idea that it's **possible** for you to open the native shell on a native IDE (Android Studio, XCode, Visual Studio, etc), but it's not the main target (and thus can be non-optimal).

**Comment by JeremyColton** [comment]
I don't open a native shell in my IDE. I use the cordova cli on the windows cmd line to manage plugins and build. I use the IDE to build the app and run it on my android phone. I also need an IDE to code the app. But if the java code doesn't compile then I can't run the app via the IDE on my phone.

So which IDE do you use to write your app?

**Comment by fredgalvao** [comment]
My setup/toolkit was/is something like this:
- use the command line to manage everything (add/remove platforms/plugins, clean/build/run) on a linux machine (another dev on the team did the same on a Macbook)
- use Jetbrain's Intellij IDEA (the same base product as Android Studio) to open the whole app root folder as a web project (with all folders properly managed, some marked as "generated/excluded output" such as `platforms` and `plugins`)
  - but I have used Brackets, VSCode, or any text editor as my "IDE", because everything was actually running on the command line
  - I have also tested with partial effort and partial success running/debugging my cordova app directly from VSCode
  - I have also, at some points in the past, opened the native shell (`platforms/android`) directly on Intellij IDEA as a simple Android Project, and I remember managing to debug some plugin I was messing around with, **because IDEA could manage and understand the gradle dependency by itself**, so that it would see/use/change the same set of files that the command line was seeing/using/changing, thus being compatible with the `cordova {clean,build,run}` commands.
  - the other dev with a macbook used XCode on the native shell folder (`platforms/ios`) alongside IDEA on the root folder, changing web code on IDEA and running/managing the native application on XCode (cordova generates a shell completely understandable by xcode, so it's a simple/valid ios project to it, and also because running cordova ios applications from the command line was not a trivial task years ago)
  - I have had other devs on the team open the native android shell on {IDEA/Android Studio} on a Windows machine too, using it to run (remember, the actual source of web code is outside the native shell folder, **changing web code inside the native shell folder directly is a hack**.

Overall, the source of truth was the `www` folder (which in my case is itself generated from another folder called `src` that I have, which is managed by gulp to do the web build process). And on top of that single source of truth, the command line was the ultimate source of action (with some IDEs doing part-time job eventually).

I don't remember having to mess too much with IDEA's module settings to make it understand my cordova android dependencies coming from gradle (and I use two projects that use them: phonegap-plugin-push and cordova-plugin-facebook4).

I don't quite remember which version of cordova-cli I was using last on my notebook, but it was something like 6.x or even 7.x (I have some commits mentioning updating output with cordova-cli 7.x, but my memory is garbage). My platform versions are:
```
    "cordova-android": "^6.2.3",
    "cordova-ios": "~4.4.0",
```

**Comment by fredgalvao** [comment]
Also, read [this](https://cordova.apache.org/docs/en/latest/guide/platforms/android/). These docs didn't even exist back when I was building my dev setup, they should be so much more updated nowadays.
And [this is another example](https://www.ibm.com/support/knowledgecenter/en/SSHS8R_8.0.0/com.ibm.worklight.dev.doc/dev/c_cord_and_cordova_app_setting_up.html) of how easy it **should** be to just open/run a cordova project on Android Studio.
