### ISSUE TITLE
Facebook Graph API forced upgrade

### ISSUE THREAD

**Issue by rolinger** [jeduan/cordova-plugin-facebook4#703]
I have been reading through various previous issues related to this subject but am still a bit unclear.  I just got the Version 2.7 is being retired email from FB.  I am on plugin version 1.9.1 which apparently still uses Graph API 2.7. 

Unfortunately, upgrading the plugin to the most recent version 2.4 breaks my app.  What version of the Graph API is used in plugin version 2.4?  How at risk am I of not upgrading the plugin and running an older version of the Graph API?  Will GA 2.7 simply stop working....or is it just not going to be supported anymore?

Cordova@8.0
Cordova-Android@7.1.1

Assuming the GA gets upgraded to something higher than 2.7, what plugin version should I try to upgrade to that should work with my deployment and upgrades to a higher GA?

**Comment by peterpeterparker** [comment]
@fredgalvao could correct me but I think that the plugin itself doesn't specify any Graph API version respectively the SDKs used by the plugin set the version

My understanding is the following:

For iOS we include and ship the Facebook iOS SDK in the plugin and it's up-to-date. Currently v2.4.0 include the very last version v4.36.0 of the Facebook iOS SDK 

For Android the Facebook Android SDK is not shipped with the plugin but resolved and bundled for example when you build your app using Cordova. Since per default we specify `ANDROID_SDK_VERSION` to `4.+` (see plugin.xml) I'm guessing that the most recent SDK will then be use (https://github.com/facebook/facebook-android-sdk)

Therefore, again if I understand correctly, in both cases we should be good

About your second question "How at risk am I of not upgrading the plugin and running an older version of the Graph API?" I can't answer that. I don't know your app, I didn't studied the messages regarding this information etc. sorry for not being able to help there

About "Unfortunately, upgrading the plugin to the most recent version 2.4 breaks my app." well you are using Cordova v8 and Cordova-Android v7.1.1 so you should be able to upgrade. My Ionic/Cordova app use the same lib and I'm using the very last version of the Facebook4 plugin v2.4.0, which I just published today after having successfully tested the login

For these reasons I close this discussion and support inquiry. But, like I said, it's my understanding. If someone notice that I'm wrong, don't hesitate to correct me and I'll reopen it

**Comment by rolinger** [comment]
Thanks for the thorough response.  I am certain this will be of help to others in the future too.  Maybe this response can be added to the Graph API section so its up front and center and helps eliminate confusion regarding the FB upgrade emails.

I too am running an Ionic/Cordova app, however I am still on Ionic v1.  I don't imagine Ionic v1 will contribute to problems upgrading from v1.9.1 to v2.4.0, but when I went through recent massive upgrades just get everything working on C@8.0 and C-A@7.1.1 it compiled cleanly with v1.9.1 I decided not to muck around with things any further.  I do recall during that upgrade time I tried using plugin version 2.1 or 2.2 and it broke...and downgrading back to 1.9.1 worked so I left it as is.  Got it working....was good enough for me at the time.  Maybe now I can readdress the specific FB plugin.  Thanks.

**Comment by peterpeterparker** [comment]
@rolinger thx you for your understanding, really cool 👍 

again this is my understanding, I think I get it, but if someone land on this and would like to correct me don't hesitate and ping me

yep Ionic itself has nothing to do with the plugin

First I'm guessing that when you say it's breaking, it's breaking on Android and not iOS. That in my experience the most common case and often the result of some cross-dependencies which doesn't like each other. In v2 of the plugin a new variable was added `ANDROID_SDK_VERSION`(see CHANGELOG) to let you specify a specific version. Maybe you will have to play with this variable or maybe you will have to to remove the Android platform and then add it again plugin after plugin...sorry I now sometimes it's difficult to bring everything together but to be fair, it's not just related to this plugin

Good luck!

P.S.: If you open a feed on the Ionic forum, feel free to link the post here
