### ISSUE TITLE
[Doc] Add a notice in the doc about the fact that the Graph API version isn't specified by the plugin itself

### ISSUE THREAD

**Issue by peterpeterparker** [jeduan/cordova-plugin-facebook4#708]
[ X] I'm reporting a feature request

**Describe the doc improvement**

To follow https://github.com/jeduan/cordova-plugin-facebook4/issues/703 and the many questions, it would be good to add a notice in the doc that the plugin itself doesn't specify a Graph API version

**Comment by peterpeterparker** [comment]
I have added a note about the Graph API in the `README` (see commit b3efd52ea4f000e69c7ebf255acc2f33a5b0446d)

FYI @fredgalvao I tried to summarize your explanation in #703 thx again

**Comment by fredgalvao** [comment]
I found this, which might explain **a lot**: https://developers.facebook.com/docs/apps/versions/

**Comment by peterpeterparker** [comment]
@fredgalvao that would mean that without specifying version the older version is used per default, but we are still not sure if the Facebook SDK set a version or not no? or do you see that differently?

**Comment by fredgalvao** [comment]
My take on that is:
- each Facebook SDK (Android, iOS or Javascript) comes with a predefined Graph API Version, and recent SDK versions have had the option to programmatically change that version to one older than the predefined. source@ https://developers.facebook.com/docs/apps/versions/ :

> Each version of the Android SDK that's released is tied to the version that's available on the date of release. This means that if you're upgrading to a new SDK you're also upgrading to the latest API version as well (although you can manually specify any earlier, available API version with GraphRequest.setVersion()). The API version is listed with the release of each version of the Android SDK.

- with that conclusion, and looking at the facebook4 version I use on my app (1.7.4), I can see it was using SDK=`4.14`, and then looking at https://developers.facebook.com/docs/android/change-log-4x I can see that `4.14` changed to use v2.7 of the Graph API, and then looking at https://developers.facebook.com/docs/graph-api/changelog/ I can see that v2.7 will be made **unavailable** after `October 5, 2018`, so I have until then to upgrade my app to a newer Facebook SDK version (minimum of `4.16.1`, which uses v2.8)


So, after so much time it seems I now understand those versions, the relationship between them, and how it affects me (and will do so in the next 21 days, how lucky am I).

And now, my conclusion/suggestion is the following:
- I think we should start mirroring the iOS and Android SDKs (Facebook SDKs) to have the same version on each release, instead of the current model which is:
    - fixed Facebook iOS SDK version
    - dynamic greedy `4.+` Facebook iOS SDK version
- with mirrored and fixed major+minor versions on each facebook4 release (like `4.36.+`), we could pin-point which plugin release uses which graph API version, so that issues like these (with users asking "am I gonna be affected by the v2.7 removal?? please help!")

I suggest that because, with the `4.+` there we can never say which actual version users are using (it depends on when they installed the plugin, among other things). And thus we can never help users answer that type of issue.

**Comment by peterpeterparker** [comment]
@fredgalvao I'm agree with your conclusion and suggestions 👍 

to reflect this I will:

- Update the default value of `FACEBOOK_ANDROID_SDK_VERSION` to v4.36.0 (current Facebook iOS SDK) in `config.xml`
- Clean the doc regarding this variable
- Add a notice about the "mirroring"

Agree or would you like to solve that differently?

**Comment by fredgalvao** [comment]
Seems pretty good to me!

**Comment by peterpeterparker** [comment]
Solved in commit b76b207e3271cbeab3cc87431fed766e80cabfe9 and published in v3.0.0

Thx @fredgalvao 👍
