### ISSUE TITLE
Upgrade the API Graph v2.9 for the Javascript platform 

### ISSUE THREAD

**Issue by dlazzy** [jeduan/cordova-plugin-facebook4#774]
**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[x] I'm reporting a feature request

**Describe the Bug of feature request**

Facebook throw an alert that the API Graph v2.9 will be outdated as of the 22 July, 2019

They say to migrate all calls to the API Graph v2.10 or above. Is the version v2.9 will cause any problems that's the quesiton...

**Plugin version, OS, devices, etc**

Plugin version 4.2.1

**Comment by dland512** [comment]
I got an email about this too (see below). I'm not directly using the methods listed by facebook, so I'm assuming this plugin is. Is that correct? And what is the best course of action here, just update to the latest version? I'm currently using version `1.9.1.`.

<img width="1057" alt="Screen Shot 2019-06-24 at 11 51 48 AM" src="https://user-images.githubusercontent.com/1686534/60037249-ac262880-9676-11e9-8e74-dcad03d22bd9.png">

**Comment by luciojb** [comment]
@dland512 same here, i really don't know if it's only upgrade the version... Maybe it has to do with the 5.0 SDK release, so maybe it has to support that SDK. I'm using the plugin with ionic, and the 5.0.0 SDK version doesn't have support.

**Comment by francois-n-dream** [comment]
We get a similar message

```
Your Facebook SDK for iOS is out of date and missing important iOS 11 fixes that make it easier for people to log into your app.
``

Any way to update the sdk?

**Comment by lopezasin** [comment]
I think we will have a big problem on July 22 :( . Please, we need a revision of the plugin. Thank you!

**Comment by peterpeterparker** [comment]
The plugin itself doesn't specify any Graph API version. Same question has been asked several times like https://github.com/jeduan/cordova-plugin-facebook4/issues/703 or https://github.com/jeduan/cordova-plugin-facebook4/issues/633

**Comment by dland512** [comment]
I apologize for my ignorance here but it's not clear to me how to proceed.

As I stated, I'm not calling any of the methods listed in the table
```
GET {application-id} 2.0
GET {user-id}/permissions 2.0
```
So why am I getting this email? Is this plugin calling these?

If I update this plugin to the latest I noticed that  the facebook error goes away.

<img width="478" alt="Screen Shot 2019-07-05 at 4 49 18 PM" src="https://user-images.githubusercontent.com/1686534/60746583-0eb7d800-9f45-11e9-847c-25ca2982bc50.png">

Of course, that requires me to release a new version of the app, which I'd prefer not to have to do.

I noticed that you also have the option of changing the API version from the apps configuration page.

<img width="986" alt="Screen Shot 2019-07-05 at 4 50 06 PM" src="https://user-images.githubusercontent.com/1686534/60746582-0bbce780-9f45-11e9-88a0-f3492fcf0082.png">

Would setting this value to a higher version fix the problem? I'm not sure how changing this setting will actually cause the SDK to use a different version of the API, but that does seem to be what it implies. Unfortunately, I haven't been able to try this on my own because I'm having build problems on Android.

**Comment by cyrilgandon** [comment]
> The plugin itself doesn't specify any Graph API version. Same question has been asked several times like #703 or #633

It seems to specify very clearly which version to use, at least for the JS part, see https://github.com/jeduan/cordova-plugin-facebook4/blob/master/www/facebook-browser.js#L159

There is a PR pending at this subject: https://github.com/jeduan/cordova-plugin-facebook4/pull/755

2.7 is deprecated since April 25, 2017... Can we have an update ?




April 25, 2017
--

**Comment by peterpeterparker** [comment]
@cyrilgandon agree on "for the JS part", I've updated my comment

instead of a merging a PR which replace a fix value by a fix value, could you provide a PR which introduce a new variable?

maybe something like 

```
<preference name="FACEBOOK_JS_API_GRAPH_VERSION" default="v4.0"/>
```

**Comment by cyrilgandon** [comment]
Looks like a good idea, I'll look into it

**Comment by peterpeterparker** [comment]
Cool, thx in advance 👍

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect`. I've made the default SDK version for the browser platform v9.0, and allowed for it to be set by the developer with a new preference:

https://www.npmjs.com/package/cordova-plugin-facebook-connect
