### ISSUE TITLE
IOS Building issue 'FBSDKCoreKit/FBSDKCoreKit.h' file not found`

### ISSUE THREAD

**Issue by lsantaniello** [jeduan/cordova-plugin-facebook4#835]
Build Error:
`/Volumes/Data/projects/ionic3/poc/poc-facebook-login-ios/platforms/ios/MyApp/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.h:13:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found`

In order to replicate issue:

1) ionic start poc-facebook-login-ios blank --type=ionic-angular
2) cd poc-facebook-login-ios
3) ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID="1234567890" --variable APP_NAME="MyFbApp"
4) npm install --save @ionic-native/facebook@4
5) ionic cordova platform add ios
6) ionic cordova build ios --prod
7) open Xcode using .xcworkspace file
8) build

**Comment by ljudbane** [comment]
I followed your instructions and xcode build was successful. But there may be differences between our environments because i use older version of cordova. But once you get the podfile into xcode project it should be the same.

#811 has a lot of good advice on what to check and do, to fix this kind of problem (cocoapods version, xcode version, podfile, pod search).

**Comment by peterpeterparker** [comment]
Yes have a look to others #811, #812 or others https://github.com/jeduan/cordova-plugin-facebook4/issues?utf8=✓&q=FBSDKCoreKit.h

Double check the documentation too, if you notice something missing don't hesitate to submit a PR to improve it.

Plz use other channels for support requests, thx in advance
